# Generated by Django 4.1.7 on 2023-05-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0005_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recapp.recette')),
            ],
        ),
    ]
