# Generated by Django 4.1.7 on 2023-05-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0006_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='text_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
